<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_TEST" Id="{01cac848-6a67-430a-a0cb-4e6885cf271a}" SpecialFunc="None">
    <Declaration><![CDATA[(*
    This is the main program for execution of the unit tests.
    The program executes the test suites one after the other, with a delay of T#5S between
    each other (that is, as soon as one test suite has finished executing, the next
    one starts to execute after a 5 second delay). This delay is defined in the parameter
    GVL_Param_TcUnit.TimeBetweenTestSuitesExecution.
    Within each test suite, the program executes each test one after the other, which
    is achieved by calling the TEST_ORDERED() for every test. The test-order is defined
    by the order of which the tests are being called.
    The tests include tests for function blocks which need several cycles to complete.
*)
PROGRAM PRG_TEST
VAR
    fbStateMachineFunctionBlock_Test : FB_StateMachineFunctionBlock_Test;
    fbTimedFunctionBlock_Test : FB_TimedFunctionBlock_Test;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN_IN_SEQUENCE();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>